AWSTemplateFormatVersion: '2010-09-09'

Description: "Regional API DNS Setup for Domain"

Parameters:

  SubDomain:
    Type: String
    Description: |
      Sub-domain to launch API domain under
    Default: api

Resources:

  ApiCloudWatchExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: !Sub "apigateway.${AWS::URLSuffix}"
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"

  ApiAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiCloudWatchExecutionRole.Arn

  ApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Sub
        - "${SubDomain}.${Domain}"
        - Domain: !ImportValue DomainName
      RegionalCertificateArn: !ImportValue DomainCertificate
      EndpointConfiguration:
        Types:
          - REGIONAL

  ApiDomainRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !ImportValue DomainId
      RecordSets:
        - SetIdentifier: !Sub
            - "A@${AWS::Region}@${SubDomain}.${DomainName}"
            - DomainName: !ImportValue DomainName
          Name: !Sub
            - "${SubDomain}.${DomainName}"
            - DomainName: !ImportValue DomainName
          Region: !Ref AWS::Region
          Type: A
          AliasTarget:
            EvaluateTargetHealth: true
            HostedZoneId: !GetAtt ApiDomainName.RegionalHostedZoneId
            DNSName: !GetAtt ApiDomainName.RegionalDomainName

Outputs:

  ApiDomainName:
    Description: The FQDN API Domain Name
    Value: !Sub
      - "${SubDomain}.${DomainName}"
      - DomainName: !ImportValue DomainName
    Export:
      Name: ApiDomainName