AWSTemplateFormatVersion: 2010-09-09

Description: "[Authentication] Service deployment"

Parameters:

  ReplyToUsername:
    Type: String
    Default: no-reply
    Description: |
      Username excluding the @domain suffix

  EmailSubject:
    Type: String
    Default: "Your temporary password"
      
  EmailMessage:
    Type: String
    Default: "Your username is {username} and temporary password is {####}."

  EmailIdentityArn:
    Type: String
    Description: The ARN of the SES Sending identity for email

  ReferralMessage:
    Type: String
    Default: "Your referral code is {####}."

  PostConfirmationMessage:
    Type: String
    Default: "Welcome {####}, sign up has completed."
      
  SMSMessage:
    Type: String
    Default: "Your username is {username} and temporary password is {####}."
      
  EmailVerificationMessage:
    Type: String
    Default: "Your verification code is {####}."
      
  EmailVerificationSubject:
    Type: String
    Default: "Your verification code"
      
  SmsAuthenticationMessage:
    Type: String
    Default: "Your authentication code is {####}."
      
  SmsVerificationMessage:
    Type: String
    Default: "Your verification code is {####}."
      
Resources:

  ReferralTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: phone_number
          AttributeType: S
        - AttributeName: referral_code
          AttributeType: S
      KeySchema:
        - AttributeName: phone_number
          KeyType: HASH
        - AttributeName: referral_code
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TimeToLiveSpecification:
        AttributeName: expires
        Enabled: true

  ReferralFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt ReferralFunctionExecutionRole.Arn
      Timeout: 20
      Runtime: nodejs6.10
      Environment:
        Variables:
          EVENT: referral.created.sendMessages
          FABRIC_TOPIC: !ImportValue Fabric
          MESSAGE_TEMPLATE: !Ref ReferralMessage
      Layers:
        - !ImportValue FabricLayer
      Code:
        ZipFile: |
          const SNS = require('aws-sdk/clients/sns');
          const fabric = require('@friendswithsitters/fabric');
          const { EVENT: event, MESSAGE_TEMPLATE: template, AWS_REGION: region } = process.env;
          const sns = new SNS({ region });

          exports.handler = ({ Records }, ctx, cb) => {
            Promise.all(Records.map(({ dynamodb: { NewImage }, eventName }) => {
              if (eventName !== 'INSERT') return true;
              return sns.publish(fabric(event, {
                MessageRequest: {
                  Addresses: {
                    [NewImage.phone_number.S]: {
                      ChannelType: 'SMS',
                    }
                  },
                  MessageConfiguration: {
                    SMSMessage: {
                      Body: template.replace('{####}', NewImage.referral_code.S),
                      MessageType: 'TRANSACTIONAL',
                      SenderId: 'Sitters',
                    },
                  },
                },
              })).promise();
            })).then(data => cb(null, data)).catch(cb);;
          };

  ReferralStream:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 5
      Enabled: true
      EventSourceArn: !GetAtt ReferralTable.StreamArn
      FunctionName: !GetAtt ReferralFunction.Arn
      StartingPosition: TRIM_HORIZON

  ReferralFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ReferralFunction}"
      RetentionInDays: 1

  ReferralFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: ExecutionPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource:
                  - !GetAtt ReferralTable.Arn
                  - !GetAtt ReferralTable.StreamArn

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      MfaConfiguration: 'OPTIONAL'
      AutoVerifiedAttributes:
        - email
        - phone_number
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: phone_number
          Required: true
          Mutable: true
        - Name: family_name
          Required: true
          Mutable: true
        - Name: name
          Required: true
          Mutable: true
        - Name: purpose
          AttributeDataType: String
          Mutable: false
        - Name: referrer_id
          Required: false
          Mutable: true
          DeveloperOnlyAttribute: true
          AttributeDataType: String
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireUppercase: true
          RequireSymbols: false
      UsernameAttributes:
        - phone_number
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
        InviteMessageTemplate:
          EmailSubject: !Ref EmailSubject
          EmailMessage: !Ref EmailMessage
          SMSMessage: !Ref SMSMessage
      EmailVerificationMessage: !Ref EmailVerificationMessage
      EmailVerificationSubject: !Ref EmailVerificationSubject
      SmsAuthenticationMessage: !Ref SmsAuthenticationMessage
      SmsVerificationMessage:  !Ref SmsVerificationMessage
      DeviceConfiguration:
        ChallengeRequiredOnNewDevice: true
        DeviceOnlyRememberedOnUserPrompt: true
      EmailConfiguration:
        SourceArn: !Ref EmailIdentityArn
        ReplyToEmailAddress: !Sub
          - "${ReplyToUsername}@${Domain}"
          - Domain: !ImportValue DomainName
      SmsConfiguration: 
        SnsCallerArn: !GetAtt SMSRole.Arn
        ExternalId:
          Fn::Base64: !Ref AWS::StackId
      LambdaConfig:
        PreSignUp: !GetAtt PreSignUpFunction.Arn
        PostConfirmation: !GetAtt PostConfirmationFunction.Arn

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool 
      ReadAttributes:
        - email
        - email_verified
        - phone_number
        - phone_number_verified
        - birthdate
        - name
        - family_name
        - updated_at
        - custom:purpose
      WriteAttributes:
        - email
        - phone_number
        - birthdate
        - name
        - family_name
        - updated_at
        - custom:purpose

  UserPoolPreSignUpFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PreSignUpFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn: !GetAtt UserPool.Arn

  UserPoolPostConfirmationFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PostConfirmationFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn: !GetAtt UserPool.Arn

  PreSignUpFunction:
    Type: AWS::Lambda::Function
    Properties:
      Timeout: 5
      Handler: index.handler
      Role: !GetAtt PreSignUpFunctionExecutionRole.Arn
      Runtime: nodejs6.10
      Environment:
        Variables:
          REFERRAL_TABLE: !Ref ReferralTable
      Code:
        ZipFile: |
          const { DynamoDB, Pinpoint, CognitoIdentityServiceProvider } = require('aws-sdk');
          const { REFERRAL_TABLE: TableName, AWS_REGION: region } = process.env;
          const dynamo = new DynamoDB.DocumentClient({ service: new DynamoDB({ region }), params: { TableName } });
          const pinpoint = new Pinpoint({ region: 'us-east-1' });

          exports.handler = (event, ctx, callback) => {
            const { userPoolId, request: { userAttributes, validationData } } = event;
            const { phone_number: phoneNumber } = userAttributes;
            const { referral_code: referralCode } = validationData;

            // exit if request is admin creating a user
            if (event.triggerSource === 'PreSignUp_AdminCreateUser') return callback(null, event);
            
            // ensure a referral code is set
            if (!referralCode) return callback(new Error('Referral code missing from sign up.'));

            // initialise cognito client
            const cognito = new CognitoIdentityServiceProvider({ region, params: { UserPoolId: userPoolId } });

            const actions = [
              // check for duplicate users with the same phone number
              cognito.listUsers({ Filter: `phone_number = \"${phoneNumber}\"` }).promise()
                .then(({ Users: users }) => {
                  if (users.length > 0) throw new Error(`Phone number "${phoneNumber}" is already registered.`);
                }),
              // ensure the number is valid and registered to a valid mobile
              pinpoint.phoneNumberValidate({ NumberValidateRequest: { PhoneNumber: phoneNumber } }).promise()
                .then(({ NumberValidateResponse: { PhoneType } }) => {
                  if (PhoneType !== 'MOBILE') throw new Error(`Phone number "${phoneNumber}" is invalid, or not a mobile number.`);
                }),
              // check that the referral code is valid
              dynamo.get({ Key: { phone_number: phoneNumber, referral_code: referralCode } }).promise()
                .then(({ Item: item }) => {
                  if (!item) throw new Error(`Referral code "${referralCode}" is invalid.`);
                }),
            ];

            Promise.all(actions).then(() => callback(null, event)).catch(callback);
          };

  PreSignUpFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${PreSignUpFunction}"
      RetentionInDays: 1

  PreSignUpFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: ExecutionPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:ListUsers
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - mobiletargeting:PhoneNumberValidate
                Resource:
                  - !Sub "arn:${AWS::Partition}:mobiletargeting:us-east-1:${AWS::AccountId}:phone/number/validate"
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                Resource:
                  - !GetAtt ReferralTable.Arn

  PostConfirmationFunction:
    Type: AWS::Lambda::Function
    Properties:
      Timeout: 5
      Handler: index.handler
      Role: !GetAtt PostConfirmationFunctionExecutionRole.Arn
      Runtime: nodejs6.10
      Environment:
        Variables:
          REFERRAL_TABLE: !Ref ReferralTable
          MESSAGE_TEMPLATE: !Ref PostConfirmationMessage
      Code:
        ZipFile: |
          const { DynamoDB, SNS, CognitoIdentityServiceProvider } = require('aws-sdk');
          const { REFERRAL_TABLE: TableName, MESSAGE_TEMPLATE: template, AWS_REGION: region } = process.env;
          const dynamo = new DynamoDB.DocumentClient({ service: new DynamoDB({ region }), params: { TableName } });
          const sns = new SNS({ region: 'eu-west-1' });

          const KeyConditionExpression = 'phone_number = :pn and referral_code > :rc';

          exports.handler = (event, ctx, callback) => {
            const { userPoolId, userName, triggerSource, request } = event;
            const { userAttributes: { phone_number: PhoneNumber, name } } = request;

            // exit if this is not a sign up trigger
            if (triggerSource !== 'PostConfirmation_ConfirmSignUp') return callback(null, event);

            // initialise cognito client
            const cognito = new CognitoIdentityServiceProvider({ region, params: { Username: userName, UserPoolId: userPoolId } });

            const actions = [
              // send a short welcome message to the user
              sns.publish({ PhoneNumber, Message: template.replace('{####}', name) }).promise(),
              // set the referrer id for the user
              dynamo.query({ KeyConditionExpression, ExpressionAttributeValues: { ':pn': PhoneNumber, ':rc': '0' } }).promise()
                .then(({ Items: [item] }) => cognito.adminUpdateUserAttributes({
                  UserAttributes: [{ Name: 'dev:custom:referrer_id', Value: item.principal_id }],
                }).promise()),
            ];

            Promise.all(actions).then(() => callback(null, event)).catch(callback);
          };

  PostConfirmationFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${PostConfirmationFunction}"
      RetentionInDays: 1

  PostConfirmationFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: ExecutionPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - cognito-idp:AdminUpdateUserAttributes
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - dynamodb:Query
                Resource:
                  - !GetAtt ReferralTable.Arn

  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties: 
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId:  !Ref UserPoolClient
          ProviderName: !Sub "cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}"    
  
  IdentityPoolRoleMap:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties: 
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated: !GetAtt AuthenticatedRole.Arn
        unauthenticated: !GetAtt UnauthenticatedRole.Arn

  AuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Federated: cognito-identity.amazonaws.com
          Action: sts:AssumeRoleWithWebIdentity
          Condition:
            ForAnyValue:StringLike:
              cognito-identity.amazonaws.com:amr: authenticated

  UnauthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Federated: cognito-identity.amazonaws.com
          Action: sts:AssumeRoleWithWebIdentity
          Condition:
            ForAnyValue:StringLike:
              cognito-identity.amazonaws.com:amr: unauthenticated

  SMSRole: 
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Sid: ""
            Effect: "Allow"
            Principal: 
              Service: "cognito-idp.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
            Condition: 
              StringEquals:
                sts:ExternalId:
                  Fn::Base64: !Ref AWS::StackId
      Policies: 
        - PolicyName: SMSPermissions
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action: 
                  - "sns:Publish"
                Resource: "*"

Outputs:

  UserPoolId:
    Description: User Pool ID
    Value: !Ref UserPool
    Export:
      Name: UserPoolId
  
  UserPoolClient:
    Description: User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: UserPoolClient

  IdentityPoolId:
    Description: Identity Pool ID
    Value: !Ref IdentityPool
    Export:
      Name: IdentityPoolId

  ReferralTable:
    Description: The name of the Referral table
    Value: !Ref ReferralTable

  ReferralTableStreamArn:
    Description: Stream ARN for Referral Table
    Value: !GetAtt ReferralTable.StreamArn

  AuthenticatedRole:
    Description: Authenticated IAM Role
    Value: !Ref AuthenticatedRole
    Export:
      Name: AuthenticatedRole

  UnauthenticatedRole:
    Description: Unauthenticated IAM Role
    Value: !Ref UnauthenticatedRole
    Export:
      Name: UnauthenticatedRole
